### ISSUE TITLE
A Malware?

### ISSUE THREAD

**Issue by atultiwariatul** [creativetimofficial/argon-design-system#104]
Hi Team, 
Hoping you guys are doing good. I am not sure If any of the library contains a malware? whenever I am loading my website for the first time and clicking anywhere it always redirects me static.olymptrade.com. If I reload the page and then again on a random click that website will be opened, So Request your help/guidance for the same.

**Comment by atultiwariatul** [comment]
Here is what I have found this Domain (http://hobfadbig.com/rMUfwtYbI7Da8hH/6934?ndn=m2) is the culprit, This is getting loaded from runtime.* file build after ng --prod build.
When I Blocked this request from chrome dev-tools website started working properly.
Any suggestion team?

![Screenshot from 2020-04-19 02-19-31](https://user-images.githubusercontent.com/1424302/79671042-e273fc00-81e4-11ea-9f1a-42ca80d47b18.png)

**Comment by atultiwariatul** [comment]
So What is found is that this issue is not with argon, but somehow some script is getting injected in runtime*.js file at the end.

**Comment by radhikamehraa** [comment]
Hi How can I integrate my org Wellness On  a platter with your data server.
I havnet started the tech development of the web portal and mobile app yet.

Thanks,

Radhika

**Comment by gagan0123** [comment]
@atultiwariatul 

Scripts from the domain hobfadbig.com are added by BSNL, and it injects certain other scripts as well originating, with IPs originating within 117.254.1.1-117.255.255.255, using HTTP protocol on port 3000. In case you're using BSNL's internet, make sure you only visit HTTPS URLs, or use a VPN.

Here's some RTI findings filed by IFF, asking BSNL about this 
https://internetfreedom.in/bsnls-code-of-misconduct/

They even replace advertisements on many sites, with their own advertisements.

**Comment by dipunj** [comment]
Using https explicitly could be a solution, but most people just type google.com in the address bar. At this point the browser doesn't know that google.com is served only via https, since the request goes via BSNL to google, but BSNL intercepts it and doesn't let your request doesn't go to google's server. They instead stick in an ad and return the respond.

Google infact redirects requests made to http://google.com to https://google.com, but for that redirection to occur, the request must first reach them. BSNL stops it midway and throw you an ad on the yet-not-redirected-to-https-page.

Pure evil. I have complained everywhere possible, but no solution.

To all the BSNL users reading this, the only solution is to use a VPN, but if you don't want that then I guess private ISPs like JioFiber, ACT, Airtel etc are the only option. I was forced to use BSNL up untill now, since my hometown didn't have anything other than Gov owned BSNL. Not anymore!! Go to hell BSNL.

<img width="1440" alt="Screenshot 2020-08-31 at 16 48 17" src="https://user-images.githubusercontent.com/23742442/91734857-16b2ec80-ebc9-11ea-82c2-13cf2c582b49.png">

**Comment by atultiwariatul** [comment]
Yes, I found multiple articles for the Same and there were lot of findings from multiple people.
Many users questions BSNL but as per them it's fair to serve ad.
