### ISSUE TITLE
The top navigation drop-down menus should transition more smoothly rather than fade in/fade out

### ISSUE THREAD

**Issue by aw236** [creativetimofficial/argon-design-system#4]
Great work. Stripe is beautiful and it's great to have the tools that make it easier to replicate their style. However, one suggestion. On Stripe.com, when you hover over "Products" then move the cursor to "Developers", the drop-down menu moves and changes shape. In your design, each has its own drop-down menu that fades-in/fades-out when you do the same thing. It would be nice to have this behavior changed to emulate Stripe's behavior.

**Comment by extrabright** [comment]
Hi,

Thanks for the feedback and your suggestion.

We are working on that. We have some ideas regarding the navigation. However, we are working on Bootstrap's methodology and its code is not as flexible as we would want in order to create more advanced animations. So, for the beginning we decided to go with simple and smooth animations that simply work and do not bloat the code. 

But, we'll add more features soon in our free and pro versions. So, stay close :)
