### ISSUE TITLE
syntax error in _icons.scss

### ISSUE THREAD

**Issue by Berger92** [creativetimofficial/argon-design-system#8]
calc() cannot take variable names with hypens:

`width: calc(100% - $icon-size-xl - 1);`

The generated css is therefore invalid, containing $icon-size-xl.

Solution:
`width: calc(100% - #{$icon-size-xl} - 1);`
Don't forget to put spaces among the hypens when it is subtraction.

**Comment by extrabright** [comment]
Hi,

Thanks for the heads up! :+1: 
I already fixed that. Soon, I will release the update with all the fixes and new features.

**Comment by alejandrom2** [comment]
Appears as though the issue has not been properly completed as the same hyphen is missing on line 25 etc.

**Comment by AarRidho** [comment]
Alternatively you can just replace the sass variables with

`$icon-size-xl` to `5rem`
`$icon-size-lg` to `4rem`
`$icon-size-sm` to `2rem`

[https://github.com/creativetimofficial/argon-design-system/blob/62db8b2add15308ca83adaf864cc6b6a929d30b7/assets/scss/custom/_variables.scss#L400](url)

**Comment by ziming** [comment]
This problem is present in all the other argon dashboard themes too (pro or normal). $icon-size-xl is used instead of it's rem value

**Comment by xXGoziXx** [comment]
This also persists on the angular argon template.

**Comment by rarestoma** [comment]
Hi,

Thank you for working with our products.

Please replace:

`width: calc(100% - $icon-size-xl - 1);`
with 
`width: calc(100% - #{$icon-size-xl} - 1);`


`width: calc(100% - $icon-size-lg - 1);`
with
`width: calc(100% - #{$icon-size-lg} - 1);`

`width: calc(100% - $icon-size-sm - 1);`
with 
wid`th: calc(100% - #{$icon-size-sm} - 1);`

`width: calc(100% - $icon-size-xs - 1);`
with
`width: calc(100% - #{$icon-size-xs} - 1);`

Please let me know if it works.

Thank you,
Rares

**Comment by xXGoziXx** [comment]
Hi,Yeah that fixed. But I just meant that it should probably fixed in the repository.Thanks, xXGoziXx 
-------- Original message --------From: rarestoma <notifications@github.com> Date: 06/05/2020  08:28  (GMT+00:00) To: creativetimofficial/argon-design-system <argon-design-system@noreply.github.com> Cc: Godstime Osarobo <nosarobo@gmail.com>, Comment <comment@noreply.github.com> Subject: Re: [creativetimofficial/argon-design-system] syntax error in _icons.scss (#8) 
Hi,
Thank you for working with our products.
Please replace:
width: calc(100% - $icon-size-xl - 1);
with
width: calc(100% - #{$icon-size-xl} - 1);
width: calc(100% - $icon-size-lg - 1);
with
width: calc(100% - #{$icon-size-lg} - 1);
width: calc(100% - $icon-size-sm - 1);
with
width: calc(100% - #{$icon-size-sm} - 1);
width: calc(100% - $icon-size-xs - 1);
with
width: calc(100% - #{$icon-size-xs} - 1);
Please let me know if it works.
Thank you,
Rares

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/creativetimofficial/argon-design-system/issues/8#issuecomment-624487062",
"url": "https://github.com/creativetimofficial/argon-design-system/issues/8#issuecomment-624487062",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by rarestoma** [comment]
Hi @xXGoziXx,

We already added it on the list for the next update and I hope we will do it as soon as possible.

Thank you,
Rares

**Comment by bilalmalkoc** [comment]
Any fix without editing source file?
